package jasko.tim.lisp;

public class SwankNotFoundException extends Exception {
   /**
    * Autogenerated.
    */
   private static final long serialVersionUID = 8760938402938723900L;

   public void printStackTrace() {
      System.err.println("*** Swank Not Found");
      super.printStackTrace();
      System.err.println("Swank Not Found *** ");
   }
}
